### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by PhoenixPeca** [pagekit/docs#23]
This bug is all bout inserting video/Image via: 

````
![](storage/image.jpg) and 
(video){"src":"storage/video.mp4"}
````

Situation:
when inserting a image named with "(" and ")"  for example : ![](storage/image(1).jpg), the (1) just destructs the external open and closing parenthesis symbol that makes the error. 

Recommendation:
I recommend the developers of this CMS to fix this problem in the next version or by renaming the file before it is stored in the storage folder....

Another bug is that I couldn't play the video using (video)
````
{"src":"storage/video.mp4"}
````

**Comment by florianletsch** [comment]
Pagekit has been rewritten in many parts for the beta version that was released a few weeks ago. If the bug still exists, please report it in the official project repository: https://github.com/pagekit/pagekit (this one here is only for the documentation). Thanks.
