### ISSUE TITLE
Guide how to install Pagekit on Google VMs.

### ISSUE THREAD

**Issue by M3pI-IIsT0** [pagekit/docs#43]
Google compute engine has now interesting price when you creating own server, but for me and maybe other is too difficult install and right setup on some linux distribution all necessary addons and extensions for proper run pagekit. Some helping guide will be awesome. Thank you.

**Comment by florianletsch** [comment]
Thanks for the idea. We have added more information about general server setup in the past few months. Please check if that already helps you. https://pagekit.com/docs/getting-started/server-configuration
