### ISSUE TITLE
Explain the UrlProvider

### ISSUE THREAD

**Issue by PremadeGames** [pagekit/docs#59]
I am currently trying to write a simple extension that adds a widget which adds a jquery plugin js + div.
The docs wrote I should use getStatic to get to my assets but it is explained how exactly or where the example folder is located.

**Comment by PremadeGames** [comment]
Addition: What I am trying to do is basically include a JS file from my extensions assets folder.

**Comment by florianletsch** [comment]
Including CSS and JS files is explained in that section: https://pagekit.com/docs/developer-basics/views-templating#working-with-assets

For CSS and JS files, don't use `getStatic`, but instead the `style()` and `script()` helpers. These can be called inside a rendered view file, or in your module definition located in your module's `index.php`.
