### ISSUE TITLE
Typography

### ISSUE THREAD

**Issue by nicolas-servain** [pagekit/docs#61]
Hi, 

How integrate Google Fonts, i don't find the header html section ? :(

**Comment by florianletsch** [comment]
An easy way would be to include the font via CSS in your theme's stylesheet:

```css
@import url(https://fonts.googleapis.com/css?family=Open+Sans);
```

In general, adding any content to the head section works using the `view.head` event. In your module's `index.php`, listen to that event and add any result to the rendered output:

``` php
//...
'events' => [ 
    'view.head' => function($event, $view) {
        $event->addResult('<link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet" type="text/css">');
    },
]
```
