### ISSUE TITLE
Add more than one css file to template.php

### ISSUE THREAD

**Issue by Fededark** [pagekit/docs#69]
How can I add more than one css file to my template.php?

I tried something like 

`<?php $view->style('theme', 'theme:css/theme.css', 'theme:css/mystyle.css' ) ?>`

But it don't work

**Comment by sondregi** [comment]
Try changing

`<?php $view->style('theme', 'theme:css/theme.css', 'theme:css/mystyle.css' ) ?>`

to 

`<?php $view->style('mytheme', 'theme:css/theme.css', 'theme:css/mystyle.css' ) ?>`

Had the same issue when to stylesheets had the same name

**Comment by overtrue** [comment]
+1, I have also puzzled over this question, after reading the source code to figure out. 😭

**Comment by florianletsch** [comment]
You are right, this will probably needed to be explained better in the docs. But here is the question to your answer.

The first parameter of the `style()` helper requires a **unique identifier** for the style. Including more than one script works by calling `style()` multiple times, and always giving a unique identifier when you include in script. 

And also, the third parameter of the `style()` helper is for **dependencies** of the script that you are including. For that, use the identifier of the script when it was registered for the first time. 

```
<?php $view->style('theme-css', 'theme:css/theme.css') ?>
<?php $view->style('theme-style', theme:css/mystyle.css', 'theme-css') `>
```

Note: This works the same for JS files, included with `sccript()`. Internally, styles and scripts are managed separately, sou you could have one stylesheet of the name `theme` and a js file of the name `theme`.
