### ISSUE TITLE
Guide to deploy pagekit in Openshift 

### ISSUE THREAD

**Issue by mtuchi** [pagekit/docs#73]
Hello!.
I want to deploy pagekit in Openshift service. 
The downside of using Openshift for this specific project is 
Openshift support up to  php 5.4. So i look a way around it and found a custom cartridge
[php7](https://github.com/pinodex/openshift-cartridge-nginx-php7) that comes with nginx.

I setup my gear in my openshift account with 3 cartridge (pagekit prerequisite).
- Nginx and PHP 7
-  MySQL 5.5
-  phpMyAdmin 4.0

Everything was good to go.
When i opened the link i got the first error 
`ERROR /var/lib/openshift/574c7d437628e18d5000020d/app-root/runtime/repo/tmp/logs directory must be writable`

After navigating to the directory that was causing the error i found out there is no `/logs` Directory
So i created the directory logs and that fixed the first error.

When i reload the page the first step is the `index.php` will lookup for installer.
Now this is where am stuck because am getting `404` saying that `....index.php/installer Not Found`

I tried a couple edit in config file of the `nginx` directory with no lucky.

The installation process work perfectly in my local machine,
The only difference is am using `Apache server` in my local machine but everything else is the same. 

Could you suggest the way around this issue,
Thank you in  advance !
`

**Comment by florianletsch** [comment]
Please check if changing your nginx configuration matches the way it is described in the docs: https://pagekit.com/docs/getting-started/server-configuration#nginx

If that doesn't solve your issue, please post your nginx configuration. For that, please open an issue in the official pagekti repo, not here in the docs. Thanks! https://github.com/pagekit/pagekit

**Comment by daveneil** [comment]
Make your nginx.conf.erb look like this and it will work .


# Enable Gzip
gzip  on;
gzip_http_version 1.0;
gzip_comp_level 2;
gzip_min_length 1100;
gzip_buffers     4 8k;
gzip_proxied any;
gzip_types
# text/html is always compressed by HttpGzipModule
text/css
text/javascript
text/xml
text/plain
text/x-component
application/javascript
application/json
application/xml
application/rss+xml
font/truetype
font/opentype
application/vnd.ms-fontobject
image/svg+xml;

gzip_static on;
gzip_proxied        expired no-cache no-store private auth;
gzip_disable        "MSIE [1-6]\.";
gzip_vary           on;

client_max_body_size 8M;

server {
    	listen  <%= ENV['OPENSHIFT_PHP_IP'] %>:<%= ENV['OPENSHIFT_PHP_PORT'] %>;
    	root    <%= ENV['OPENSHIFT_REPO_DIR'] %>/public;
	
	
	location ~* ^.+\.(css|js|jpg|jpeg|gif|png|ico|gz|svg|svgz|ttf|otf|woff|eot|mp4|ogg|ogv|webm)$ {
		access_log off;
		log_not_found off;

		# Some basic cache-control for static files to be sent to the browser
		expires max;
		add_header Pragma public;
		add_header Cache-Control "public, must-revalidate, proxy-revalidate";
	}
	
	
    	location / {
    		try_files $uri $uri/ /index.php?$args;
        	index index.php  index.html index.htm;
    	}
	
	# pass the PHP scripts to PHP-FPM
	location ~ \.php$ {
    		fastcgi_pass unix:<%= ENV['OPENSHIFT_PHP_SOCKET'] %>;
    		fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    		fastcgi_param PATH_INFO $fastcgi_script_name;
    		include <%= ENV['OPENSHIFT_PHP_DIR'] %>/usr/conf/fastcgi_params;
	}
}
